export default {
  RED: (...args: any[]) => console.log(`\x1b[31m${args}\x1b[0m`),
  GREEN: (...args: any[]) => console.log(`\x1b[32m${args}\x1b[0m`),
  YELLOW: (...args: any[]) => console.log(`\x1b[33m${args}\x1b[0m`),
  BLUE: (...args: any[]) => console.log(`\x1b[34m${args}\x1b[0m`),
  MAGENTA: (...args: any[]) => console.log(`\x1b[35m${args}\x1b[0m`),
  CYAN: (...args: any[]) => console.log(`\x1b[36m${args}\x1b[0m`),
  WHITE: (...args: any[]) => console.log(`\x1b[37m${args}\x1b[0m`),
  BLACK: (...args: any[]) => console.log(`\x1b[30m${args}\x1b[0m`),
  DEFAULT: (...args: any[]) => console.log(`\x1b[39m${args}\x1b[0m`),

  BRIGHT_RED: (...args: any[]) => console.log(`\x1b[91m${args}\x1b[0m`),
  BRIGHT_GREEN: (...args: any[]) => console.log(`\x1b[92m${args}\x1b[0m`),
  BRIGHT_YELLOW: (...args: any[]) => console.log(`\x1b[93m${args}\x1b[0m`),
  BRIGHT_BLUE: (...args: any[]) => console.log(`\x1b[94m${args}\x1b[0m`),
  BRIGHT_MAGENTA: (...args: any[]) => console.log(`\x1b[95m${args}\x1b[0m`),
  BRIGHT_CYAN: (...args: any[]) => console.log(`\x1b[96m${args}\x1b[0m`),
  BRIGHT_WHITE: (...args: any[]) => console.log(`\x1b[97m${args}\x1b[0m`),
  BRIGHT_BLACK: (...args: any[]) => console.log(`\x1b[90m${args}\x1b[0m`), // Often looks like Gray

  BG_RED: (...args: any[]) => console.log(`\x1b[41m${args}\x1b[0m`),
  BG_GREEN: (...args: any[]) => console.log(`\x1b[42m${args}\x1b[0m`),
  BG_YELLOW: (...args: any[]) => console.log(`\x1b[43m${args}\x1b[0m`),
  BG_BLUE: (...args: any[]) => console.log(`\x1b[44m${args}\x1b[0m`),
  BG_MAGENTA: (...args: any[]) => console.log(`\x1b[45m${args}\x1b[0m`),
  BG_CYAN: (...args: any[]) => console.log(`\x1b[46m${args}\x1b[0m`),
  BG_WHITE: (...args: any[]) => console.log(`\x1b[47m${args}\x1b[0m`),
  BG_BLACK: (...args: any[]) => console.log(`\x1b[40m${args}\x1b[0m`),
  BG_DEFAULT: (...args: any[]) => console.log(`\x1b[49m${args}\x1b[0m`),

  BG_BRIGHT_RED: (...args: any[]) => console.log(`\x1b[101m${args}\x1b[0m`),
  BG_BRIGHT_GREEN: (...args: any[]) => console.log(`\x1b[102m${args}\x1b[0m`),
  BG_BRIGHT_YELLOW: (...args: any[]) => console.log(`\x1b[103m${args}\x1b[0m`),
  BG_BRIGHT_BLUE: (...args: any[]) => console.log(`\x1b[104m${args}\x1b[0m`),
  BG_BRIGHT_MAGENTA: (...args: any[]) => console.log(`\x1b[105m${args}\x1b[0m`),
  BG_BRIGHT_CYAN: (...args: any[]) => console.log(`\x1b[106m${args}\x1b[0m`),
  BG_BRIGHT_WHITE: (...args: any[]) => console.log(`\x1b[107m${args}\x1b[0m`),
  BG_BRIGHT_BLACK: (...args: any[]) => console.log(`\x1b[100m${args}\x1b[0m`),

  BOLD: (...args: any[]) => console.log(`\x1b[1m${args}\x1b[0m`),
  DIM: (...args: any[]) => console.log(`\x1b[2m${args}\x1b[0m`),
  ITALIC: (...args: any[]) => console.log(`\x1b[3m${args}\x1b[0m`),
  UNDERLINE: (...args: any[]) => console.log(`\x1b[4m${args}\x1b[0m`),
  BLINK: (...args: any[]) => console.log(`\x1b[5m${args}\x1b[0m`),
  REVERSE: (...args: any[]) => console.log(`\x1b[7m${args}\x1b[0m`),
  HIDDEN: (...args: any[]) => console.log(`\x1b[8m${args}\x1b[0m`),
  STRIKETHROUGH: (...args: any[]) => console.log(`\x1b[9m${args}\x1b[0m`),
};
